#ifndef PANTHERA_FORWARD_IOKIT_HIDSYSTEM_IOHIDPARAMETER_H
#define PANTHERA_FORWARD_IOKIT_HIDSYSTEM_IOHIDPARAMETER_H

#include "../../../../../src/IOHIDFamily-2008.40.6/IOHIDSystem/IOKit/hidsystem/IOHIDParameter.h"

#endif
