#ifndef PANTHERA_CONFIGD_MACH_SYNC_IPC_H
#define PANTHERA_CONFIGD_MACH_SYNC_IPC_H

#include <mach/mach.h>

#ifndef MACH_SEND_FILTER_NONFATAL
#define MACH_SEND_FILTER_NONFATAL 0x00010000
#endif

#ifndef MACH_SEND_PROPAGATE_QOS
#define MACH_SEND_PROPAGATE_QOS 0x00400000
#endif

#endif /* PANTHERA_CONFIGD_MACH_SYNC_IPC_H */
