#ifndef PANTHERA_FORWARD_IOKIT_USB_APPLEUSBDIAGNOSTICS_H
#define PANTHERA_FORWARD_IOKIT_USB_APPLEUSBDIAGNOSTICS_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/AppleUSBDiagnostics.h"

#endif
