#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBHUBPOLICYMAKER_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBHUBPOLICYMAKER_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBHubPolicyMaker.h"

#endif
