#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBROOTHUBDEVICE_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBROOTHUBDEVICE_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBRootHubDevice.h"

#endif
