#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERLISTELEMENT_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERLISTELEMENT_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBControllerListElement.h"

#endif
