#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBCOMPOSITEDRIVER_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBCOMPOSITEDRIVER_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBCompositeDriver/Headers/IOUSBCompositeDriver.h"

#endif
