#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBINTERFACEUSERCLIENT_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBINTERFACEUSERCLIENT_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBUserClient/Headers/IOUSBInterfaceUserClient.h"

#endif
