#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERV2_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERV2_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBControllerV2.h"

#endif
