#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERV3_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERV3_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBControllerV3.h"

#endif
