#ifndef PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERUSERCLIENT_H
#define PANTHERA_FORWARD_IOKIT_USB_IOUSBCONTROLLERUSERCLIENT_H

#include "../../../../src/IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBControllerUserClient.h"

#endif
