#ifndef PANTHERA_FORWARD_IOKIT_HIDEVENT_IOHIDEVENTSERVICE_H
#define PANTHERA_FORWARD_IOKIT_HIDEVENT_IOHIDEVENTSERVICE_H

#include "../../../../src/IOHIDFamily-2008.40.6/IOHIDFamily/IOHIDEventService.h"

#endif
