#ifndef PANTHERA_ZFS_CONFIG_H
#define PANTHERA_ZFS_CONFIG_H

#define ZFS_META_NAME "zfs"
#define ZFS_META_VERSION "2.3.1"
#define ZFS_META_RELEASE "panthera"
#define ZFS_META_ALIAS "zfs-2.3.1-panthera"
#define ZFS_META_AUTHOR "OpenZFS"
#define ZFS_META_LICENSE "CDDL"
#define ZFS_META_VERSION_RELEASE ZFS_META_VERSION "-" ZFS_META_RELEASE

#define STDC_HEADERS 1
#define HAVE_DECL_STRLCAT 1
#define HAVE_DECL_STRLCPY 1
#define HAVE_EFFICIENT_UNALIGNED_ACCESS 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1

#define HAVE_PAGEOUT_V2 1

#endif /* PANTHERA_ZFS_CONFIG_H */
