#ifndef PANTHERA_WRAPPER_IOKIT_HID_APPLEHIDUSAGETABLES_H
#define PANTHERA_WRAPPER_IOKIT_HID_APPLEHIDUSAGETABLES_H

#include "../../../../src/IOHIDFamily-2008.40.6/IOHIDFamily/AppleHIDUsageTables.h"

#endif
