#ifndef PANTHERA_FORWARD_IOKIT_HID_IOHIDEVENTSERVICEKEYS_PRIVATE_H
#define PANTHERA_FORWARD_IOKIT_HID_IOHIDEVENTSERVICEKEYS_PRIVATE_H

#include "../../../../src/IOHIDFamily-2008.40.6/IOHIDFamily/IOHIDEventServiceKeys_Private.h"

#endif
