#ifndef PANTHERA_FORWARD_IOKIT_HID_IOHIDEVENTSERVICETYPES_H
#define PANTHERA_FORWARD_IOKIT_HID_IOHIDEVENTSERVICETYPES_H

#include "../../../../src/IOHIDFamily-2008.40.6/IOHIDFamily/IOHIDEventServiceTypes.h"

#endif
